#!/bin/sh
php_version='8.0.19'
redis_version='5.3.4'
yum -y install epel-release pcre pcre-devel zlib-devel zlib libxml2-devel libxml2 openssl openssl-devel libcurl libcurl-devel libjpeg-turbo-devel libjpeg-turbo libpng-devel libpng libXpm-devel libXpm freetype-devel libpng-devel libvpx-devel mysql-devel postgresql-devel sqlite-devel libwebp-devel oniguruma-devel; yum update
cd /root/sources
wget https://www.php.net/distributions/php-${php_version}.tar.gz
wget https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/libzip-devel-1.6.1-1.module_el8.3.0+396+9a0d79d6.x86_64.rpm
wget https://vault.centos.org/centos/8/AppStream/x86_64/os/Packages/libzip-1.6.1-1.module_el8.3.0+396+9a0d79d6.x86_64.rpm
yum install libzip-1.6.1-1.module_el8.3.0+396+9a0d79d6.x86_64.rpm libzip-devel-1.6.1-1.module_el8.3.0+396+9a0d79d6.x86_64.rpm
tar zxvf php-${php_version}.tar.gz
cd php-${php_version}
./configure \
        --prefix=/opt/php80 \
        --enable-gd=/usr/lib64/ \
        --with-jpeg \
        --with-freetype \
        --with-webp \
        --with-xpm \
        --with-zlib \
        --enable-sysvshm \
        --with-openssl \
        --with-pgsql \
        --enable-soap \
        --with-curl \
        --with-libdir=/usr/lib64/ \
        --enable-xml \
        --enable-session \
        --enable-cli \
        --with-iconv \
        --enable-simplexml \
        --enable-ctype \
        --enable-filter \
        --enable-ftp \
        --enable-xmlreader \
        --enable-phar \
        --with-pear \
        --enable-fpm \
        --enable-dom \
        --enable-pdo \
        --enable-mbstring \
        --with-pdo-mysql \
        --with-pdo-pgsql \
        --with-zip \
        --enable-mysqlnd \
        --with-mysqli \
        --with-libxml \
        --enable-sockets \
        --enable-opcache;
        make; \
        make install
echo
echo install module redis
echo
cd /root/sources
wget https://pecl.php.net/get/redis-${redis_version}.tgz; tar zxvf redis-${redis_version}.tgz
cd /root/sources/redis-${redis_version}
/opt/php80/bin/phpize .
./configure --with-php-config=/opt/php80/bin/php-config;make ; make install
echo
echo install module mcrypt
echo
cd /root/sources
wget https://pecl.php.net/get/mcrypt-1.0.5.tgz;tar xvf mcrypt-1.0.5.tgz
cd /root/sources/mcrypt-1.0.5
/opt/php80/bin/phpize .
./configure --with-php-config=/opt/php80/bin/php-config;make ;make install
echo
echo Install psr module untuk phalcon
cd /root/sources
wget https://pecl.php.net/get/psr-1.2.0.tgz;tar xvf psr-1.2.0.tgz
cd /root/sources/psr-1.2.0
/opt/php80/bin/phpize .
./configure --with-php-config=/opt/php80/bin/php-config;make ;make install